trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: "Login docker registry"
    inputs:
       command: login
       containerRegistry: quay.io/openshift-operators

  - task: Docker@2
    displayName: "Build super-project operator image"
    inputs:
      Dockerfile: "**/build/Dockerfile"
      buildContext: "."
      command: buildAndPush
      repository: openshift-operators/super-project
      tags: |
        latest



