---
- include_tasks: project.yaml
- include_tasks: useroot.yaml
- include_tasks: limit_range_quota.yaml
- include_tasks: network_policy.yaml
- include_tasks: pull_infra_secrets.yaml
- include_tasks: argocd_project.yaml
- include_tasks: jenkins.yaml


