- set_fact:
      global_project_name: "{{ meta.name.split('-')[0] }}"

- set_fact:
    kv_mount_path: "/kv"
    secret_path: "ocp/projects/{{ global_project_name }}/infra"
    vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
    vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
- block:
  - name: Check if current path exists
    uri:
      url: "{{ vault_addr }}/v1/{{ kv_mount_path }}/metadata/{{ secret_path }}"
      headers:
        X-Vault-Token: "{{ vault_token }}"
      method: LIST
      follow_redirects: all
      validate_certs: no
      body_format: json
      status_code:
        - 200
        - 404
    register: path_stat

  - name: Create infrastructure secret pulled from Hashicorp Vaulto
    k8s:
      state: present
      apply: yes
      definition: "{{ lookup ('template', 'infra-secret.yaml') | from_yaml  }}"
    vars:
      full_secret_path: "{{ kv_mount_path }}/data/{{ secret_path }}/{{ secret_name }}"
      namespace: "{{ meta.name }}"
      secret_name: "{{ secret_name }}"
    loop:  "{{ path_stat.json.data['keys'] }}"
    loop_control:
      loop_var: secret_name
    when: path_stat.status  == 200
  when:
    - vault_addr != ''
    - vault_token != ''

#ocr-service-account - secret with credentials to internal docker registry