apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: superprojects.automation.ocp.io
spec:
  group: automation.ocp.io
  names:
    kind: Superproject
    listKind: SuperprojectList
    plural: superprojects
    singular: superproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
