---
apiVersion: v1
data:
{% set secret = lookup('hashi_vault', 'secret={{ full_secret_path }} validate_certs=False') %}
{% for k,v in secret.data.items() %}
  {{ k }}: {{ v | b64encode }}
{% endfor %}
kind: Secret
metadata:
  name: "{{ secret_name }}"
  namespace: "{{ namespace }}"
  labels:
          "credential.sync.jenkins.openshift.io": "true"
  annotations:
        "jenkins.openshift.io/secret.name": "{{ secret_name  }}"

type: kubernetes.io/basic-auth