apiVersion: "v1"
kind: ServiceAccount
metadata:
  namespace: "{{ meta.name }}"
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name": "{{ jenkins_service_name }}" }}'
  name: "{{ jenkins_service_name }}"